Track balance of due payments to DDC (total for cluster)
Cerebellum-Network/ddc-smart-contract pull request #40
Opened 2021-06-15 14:53 UTC by evgeny-s

[Ticket](https://cerenetwork.atlassian.net/browse/CBI-906)
* Added total_ddc_balance. Put consumed balance to this state.

2021-06-16 12:53 UTC, naure requested changes

2021-06-16 12:53 UTC, naure commented on src/lib.rs
> +            Self::actualize_subscription(subscription, subscription_tier);
Incorrect, this loses track of `consumed` amount.

2021-06-16 12:53 UTC, naure commented on src/lib.rs
> +            Self::actualize_subscription(subscription, subscription_tier);
Same.

2021-06-16 12:53 UTC, naure commented on src/lib.rs
> +        fn actualize_subscription(
It’s very important to not forget to track `consumed`. You can add `#[must_use]` to the functions to generate a warning.

https://doc.rust-lang.org/reference/attributes/diagnostics.html#the-must_use-attribute

2021-06-16 14:13 UTC, evgeny-s commented on src/lib.rs
> +        fn actualize_subscription(
Added attribute, also fixed all warnings.
Thanks!

2021-06-16 14:13 UTC, evgeny-s commented on src/lib.rs
> +            Self::actualize_subscription(subscription, subscription_tier);
Fixed

2021-06-16 14:13 UTC, evgeny-s commented on src/lib.rs
> +            Self::actualize_subscription(subscription, subscription_tier);
Fixed

2021-06-16 14:14 UTC, evgeny-s commented
@naure , 
Since now we can move `timestamp`, I'm going to add more tests to cover this without isolated timestamp.

2021-06-21 11:25 UTC, naure approved these changes

2021-06-21 12:18 UTC, merged