Validate metrics
Cerebellum-Network/ddc-smart-contract pull request #43
Opened 2021-06-17 09:04 UTC by doasync

2021-06-21 16:06 UTC, doasync commented
Fixed conflicts

2021-06-23 10:27 UTC, naure requested changes
Great technique! Nice cleanups too.

I think there is a little bug, see comment.

2021-06-23 10:27 UTC, naure commented on src/lib.rs
> +            self.metrics_ddn.get(&day_key).cloned()
Why remove this check?

// Return metrics that exists and is **not outdated**.

If the inspector did not report on that day, then there will still be the old data from the previous period. That’s because we reuse the same storage cells by using the same `day % PERIOD_DAYS` over multiple periods.

You need to check `metrics.start_ms` and return `None` if it’s outdated.

2021-06-23 11:43 UTC, doasync commented on src/lib.rs
> +            self.metrics_ddn.get(&day_key).cloned()
There was an issue with this code. It should not return a zero metric if there is no metric for that inspector in order to correctly calculate the median value.

> If the inspector did not report on that day, then there will still be the old data from the previous period. That’s because we reuse the same storage cells by using the same day % PERIOD_DAYS over multiple periods.
Thanks, nice observation! We definitely need a test for that. Let me write some

2021-06-23 14:15 UTC, naure commented on src/lib.rs
> +            self.metrics_ddn.get(&day_key).cloned()
Yes, now it should not return 0, but None (then not included in median).

2021-06-24 08:35 UTC, doasync commented on src/lib.rs
> +            self.metrics_ddn.get(&day_key).cloned()
@naure, I added [the check](https://github.com/Cerebellum-Network/ddc-smart-contract/pull/43/files#diff-b1a35a68f14e696205874893c07fd24fdb88882b47c23cc0e0c80a30c7d53759R1097-R1108) to `metrics_for_ddn_day`. I also wrote tests for `metrics_for_period` ([1](https://github.com/Cerebellum-Network/ddc-smart-contract/pull/43/files#diff-844c660f141ca78937b77359fb8331c8d332a6c593da827ac5ebd2bb3049640cR1371)) and `metrics_for_ddn` ([2](https://github.com/Cerebellum-Network/ddc-smart-contract/pull/43/files#diff-844c660f141ca78937b77359fb8331c8d332a6c593da827ac5ebd2bb3049640cR3168-R3175)) to make sure they produce correct values on a repeating cycle.

2021-06-24 10:03 UTC, naure approved these changes

2021-06-24 11:34 UTC, merged